### ISSUE TITLE
one GO to multiple GOs ?

### ISSUE THREAD

**Issue by BinhongLiu** [cbrl-nuces/GOntoSim#1]
Hi,
     I found that you've prepared two functions, `Similarity_of_Two_GOTerms` and `Similarity_of_Set_of_GOTerms`, for one GO to one GO and multiple GOs to multiple GOs calculation, respectively. However, I encountered that protein A had one GO annotation and B had multiple GO annotations. How should I deal with this calculation? Thanks!
Best wishes!

**Comment by A-Kamran** [comment]
In this scenario, to calculate the similarity between Protein A (which has one GO annotation) and Protein B (which has multiple GO annotations), you can use the  'Similarity_of_Set_of_GOTerms' function. Here's how you can do it:

method = 'GOntoSim'
Protein_A = ['GO:0004556']
Protein_B  = ['GO:0004556', 'GO:2001070', 'GO:0005509', 'GO:0000287']
Similarity_of_Set_of_GOTerms(Protein_A, Protein_B, method )

This should provide you with the similarity score you need for your analysis. Hope this helps. 
If you have any more questions or need further assistance, feel free to ask!



> Hi,
> I found that you've prepared two functions, `Similarity_of_Two_GOTerms` and `Similarity_of_Set_of_GOTerms`, for one GO to one GO and multiple GOs to multiple GOs calculation, respectively. However, I encountered that protein A had one GO annotation and B had multiple GO annotations. How should I deal with this calculation? Thanks!
> Best wishes!

**Comment by BinhongLiu** [comment]
Thanks for your prompt reply! It worked. Thanks.
